module.exports = {
    application: null,
    barHolder: [],
    buttonActive: 'TextNotes',
    navigation: null,
    headerTitles: [],
    SettingsScreen: null,
    GalleryScreen: null,
    TextNotesScreen: null,
    LocationScreen: null,
    darkMode: null,
    applicationGuide: null,
    LocationButton: null,
    mapReference: null,
    mapComponent: null,
    mapLocation: null,
    TextButton: null,
    ImagePickerButton: null,
    ImageTakerButton: null,
    GalleryImages: [],
    TextNotes: [],
    orientation: "Portrait",
    TextNotesWidth: null,
    TextNoteColumns: 2,
    NavBarHeight: 60,
}